### ISSUE TITLE
Page catalog link mismatch

### ISSUE THREAD

**Issue by ZipCPU** [projf/projf-explore#96]
Thank you for your wonderful video blog series!

Just a comment to help out: In the beginning of each [projectf blog article](http://projectf.io), there's a catalog of articles.  On the first article, I can click on the [hardware sprites](https://projectf.io/posts/hardware-sprites/) article.  Once there, the article marks itself as the Ad Astra article, and I cannot click on Ad Astra.  However, if I then click on the [Frame buffers](https://projectf.io/posts/framebuffers/) article, I can then click on the [Ad Astra](https://projectf.io/posts/fpga-ad-astra/) article to get there.  Once there, however, the Hardware Sprites article link is no longer available.

Thought you might wish to fix this.  Again, thank you for the wonderful series!

**Comment by WillGreen** [comment]
Thanks for reporting this. I've fixed the blog links.

Regards,
Will
